### PR TITLE
Wait until populateService is finished

### PR DESCRIPTION
**Pull request by martinheidegger**
Like in https://github.com/SC5/serverless-mocha-plugin/pull/54 this PR waits until populateService is finished, making sure that no timing problems occur.

_Note: I updated the dependencies as well, since they seemed severely out-of-date_

### CODE REVIEW

**Comment by martinheidegger** [comment]
Fixes #5

**Comment by alexdebrie** [comment]
Hey @mpuittinen, could we get this merged? Having the same problem with v1.13+ of the Framework, and I can confirm this fix solves the issue.

Awesome plugin, by the way. Makes it much easier to handle secrets!

**Comment by mpuittinen** [comment]
@martinheidegger @alexdebrie this has now been merged and has been published version 0.9.6 on the plugin. Thanks @martinheiddegger!

**Comment by alexdebrie** [comment]
Thanks @mpuittinen and thanks @martinheidegger!

**Pull request merged**
